django/core/urls.py
from django.urls import re_path

from . import views

app_name = "core"
urlpatterns = [
    re_path(r"^terms-conditions/$", views.TermsConditionsView.as_view(), name="terms-conditions"),
    re_path(r"^privacy-policy/$", views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    re_path(r"^contact-us/$", views.ContactUsView.as_view(), name="contact-us"),
    re_path(r"^about-us/$", views.AboutUsView.as_view(), name="about-us"),
    re_path(r"^faqs/$", views.FAQView.as_view(), name="faqs"),
    re_path("", views.HomeView.as_view(), name="index"),
]

django/gallery/urls.py
from django.urls import re_path

from . import views

app_name = "gallery"
# fmt: off
urlpatterns = [
    re_path(r"^delete/(?P<slug>.*)/$", views.GalleryDeleteView.as_view(), name="gallery-delete"),
    re_path(r"^detail/(?P<slug>.*)/$", views.GalleryDetailView.as_view(), name="gallery-detail"),
    re_path(r"^update/(?P<slug>.*)/$", views.GalleryUpdateView.as_view(), name="gallery-update"),
    re_path(r"^collections/$", views.GalleryListView.as_view(), name="gallery-list"),
    re_path(r"^new/$", views.GalleryCreateView.as_view(), name="gallery-create"),
    re_path(r"^photo/detail/(?P<slug>.*)/$", views.PhotoDetailView.as_view(), name="photo-detail"),
    re_path(r"^photo/delete/(?P<slug>.*)/$", views.PhotoDeleteView.as_view(), name="photo-delete"),
    re_path(r"^photo/update/(?P<slug>.*)/$", views.PhotoUpdateView.as_view(), name="photo-update"),
    re_path(r"^photo/update-cover/(?P<pk>\d+)/$", views.photo_cover_update, name="photo-cover-update"),
    re_path(r"^photo/transfer/(?P<pk>\d+)/$", views.photo_transfer, name="photo-transfer"),
    re_path(r"^category/(?P<slug>.*)/$", views.CategoryDetailView.as_view(), name="category-detail"),
]
# fmt: on

django/photoshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(r"^api/", include("core.api.urls")),
    re_path(r"^account/", include("allauth.urls")),
    re_path(r"^account/", include("users.urls")),
    re_path(r"^gallery/", include("gallery.urls")),
    re_path(r"", include("core.urls")),
]


# DEBUG TOOLBAR
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.insert(0, re_path("__debug__/", include(debug_toolbar.urls)))

django/templates/snippets/about_us.html
{% extends 'base.html' %}
{% load static  core_extras %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock extra_head %}

{% block content %}
<section id="about_us" class=" bg-white pb-32">

  <div class="2xl:container 2xl:mx-auto lg:py-16 lg:px-20 md:py-12 md:px-6 py-9 px-4">
    <div class="flex flex-col lg:flex-row justify-between gap-8 place-items-center">
      <div class="w-full lg:w-5/12 flex flex-col justify-center">
        <h1 class="text-3xl lg:text-4xl font-bold leading-9 text-gray-800 pb-4">About Us</h1>
        <p class="font-normal text-base leading-6 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro soluta dolorum placeat, pariatur eveniet tempora aliquam, aperiam iusto delectus illo beatae
          distinctio? Dolores aperiam
          quod ut officiis, rerum magnam rem!</p>
      </div>
      <div class="w-full lg:w-8/12">
        <img class="w-full h-1/2" src="{% static 'assets/images/instagram_viral.png' %}" alt="viral post" style="max-height:700px" />
      </div>
    </div>
    <div class="flex lg:flex-row flex-col justify-between gap-8 pt-12">
      <div class="w-full lg:w-5/12 flex flex-col justify-center">
        <h1 class="text-3xl lg:text-4xl font-bold leading-9 text-gray-800 pb-4">Meet The Developer</h1>
        <p class="font-normal text-base leading-6 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima doloribus voluptatibus tempore quo tenetur totam, natus ipsum esse sunt praesentium
          expedita a enim hic cupiditate velit
          exercitationem porro. Sapiente, nemo?</p>

      </div>
      <div class="w-full lg:w-8/12 lg:pt-8">
        <div class="grid md:grid-cols-4 sm:grid-cols-2 grid-cols-1 lg:gap-4 shadow-lg rounded-md">
          <div class="p-4 pb-6 flex justify-center flex-col items-center">
            <a class="text-center w-full" href="http://github.com/cbedroid" target="_blank" rel="noopener noreferrer">
              <img class="rounded-md" src="{% static 'assets/images/cbedroid.jpg' %}" alt="cedroid" style="height:185px;width:175px">
              <i class="fa fa-github text-center w-full"> cbedroid</i>
              <span class="inline-block text-xl text-gray-800 mt-4">Cornelius</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% comment %} <div class="container mx-auto">
    <div class="row">
      <div class="aboutus ">
        <div class="header text-center">
          <h1 class="heading-title horizontal-outline font-bold pb-12"> Who We Are</h1>
        </div>
        <p class="px-sm-3">
          We are a veteran owned and operated company, dedicated to improving training practices in the DOD, public and private sectors. Current legacy training methodology used to assess competency and perform workforce
          development, especially
          in a remote/hybrid work environment is either overly
          cumbersome or non-existent. We utilize SMS-enabled technology to turn mobile devices into
          micro-learning and assessment platforms, significantly improving your current business practices, training systems and personal professional growth.
        </p>
      </div>
      <div class="contact-us p-2">
        <h1 class="heading-title">Contact Us</h1>
        <ul class="social-links social-links--outline hoverable">
          <li class="social-items twitter">
            <a rel="noopener" href="https://twitter.com/tedtextllc" target="_blank">
              <i class="fa fa-twitter border-prime"></i></a>
          </li>

          <li class="social-items linkedin">
            <a rel="noopener" href="https://www.linkedin.com/company/ted-text-llc" target="_blank">
              <i class="fa fa-linkedin-square border-prime"></i></a>
          </li>
        </ul>
        <table class="table m-sm-auto p-none my-sm-3">
          <tbody>
            <tr>
              <th scope="row">Contact:</th>
              <td>
                <i class="fa fa-phone-alt d-none d-sm-inline me-2"></i>
                {% contact_phone_number %}
              </td>
            </tr>
            <tr>
              <th scope="row">Email:</th>
              <td class="ms-5">
                <i class="fas fa-envelope d-none d-sm-inline me-2"></i>
                {% tech_support_link %}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div> {% endcomment %}
</section>
{% endblock content %}

django/templates/snippets/alert_message.html
{% load static %}
<div id="alert_message" class="flex flex-col space-y-2 w-full bg-transparent ">
  {% for message in messages %}
  <div class="alert alert-{{message.tags}} flex w-full">
    <span class="text-center mx-auto">{{message}}</span>
    <button type=" button" class="close " data-dismiss="alert" aria-label="Close">
      <svg class=" hover:text-gray-600 align-middle" viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
    </button>
  </div>
  {% endfor %}
</div>

django/templates/snippets/footer.html
{% load static  %}
{% block extra_head %}
<style>
  section {
    margin: 0;
  }
</style>
{% endblock extra_head %}
<section id="footer_section" class="bg-gray-800 text-white w-sreen">
  <div class="container py-12">
    <div class="pt-12 xl:pt-14 px-6">
      <div tabindex="0" aria-label="footer" class="focus:outline-none border-gray-300 border-t lg:w-11/12 md:w-11/12 lg:mx-auto md:mx-auto">
        <div class="grid grid-cols-2 sm:grid-cols-3">
          <div class="footer-content content--left col-span-3 sm:col-span-3 lg:col-span-2">
            <div class="text-left md:text-center xl:flex lg:flex sm:flex space-y-12  sm:space-y-0 pt-6">
              {% comment %} <div class="flex-1">
                <h2 tabindex="0" class="focus:outline-none text-gray-200 font-bold text-xl mb-6">Community</h2>
                <ul>
                  <li class=" text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">About Us</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">Guidelines and how to</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">Quote from the best</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">How to start a blog</a>
                  </li>
                </ul>
              </div> {% endcomment %}
              <div class="flex-1">
                <h2 tabindex="0" class="focus:outline-none text-gray-200 font-bold text-xl mb-6">Getting Started</h2>
                <ul>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="{% url 'core:faqs' %}">Frequently Asked Questions</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">

                    <a tabindex="0" class="focus:underline focus:outline-none" href="{% url  'core:about-us' %}">About Us</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="{% url 'core:contact-us' %}">Contact Us</a>
                  </li>

                </ul>
              </div>
              {% comment %} <div class="flex-1">
                <h2 tabindex="0" class="focus:outline-none text-gray-200 font-bold text-xl mb-6">Resources</h2>
                <ul>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">Accessibility</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">Usability</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">Marketplace</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">Design & Dev</a>
                  </li>
                  <li class="text-gray-200 hover:text-gray-400 mb-5">
                    <a tabindex="0" class="focus:underline focus:outline-none" href="javascript:void(0)">Marketplace</a>
                  </li>
                </ul>
              </div> {% endcomment %}
            </div>
          </div>
          <div class="hidden lg:block mt-6">
            <h2 tabindex="0" class=" flex focus:outline-none text-gray-200 font-bold text-xl mb-6 w-full xl:justify-end">Stay Connected</h2>
            <div class="flex justify-start sm:justify-start xl:justify-end space-x-6 pr-2 xl:pr-0 lg:pr-0 md:pr-0 sm:pr-0">
              <div class="hover:bg-gray-100 hover:bg-opacity-10 p-1 rounded-md">
                <a aria-label="Twitter" role="link" href="https://twitter.com/cbedroid" rel="noopener noreferrer" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#718096" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-twitter">
                    <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
                  </svg>
                </a>
              </div>
              <div class="hover:bg-gray-100 hover:bg-opacity-10 p-1 rounded-md">
                <a aria-label="Instagram" role="link" href="javascript:void(0)" rel="noopener noreferrer" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#718096" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-instagram">
                    <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                  </svg>
                </a>
              </div>
              <div class="hover:bg-gray-100 hover:bg-opacity-10 p-1 rounded-md">
                <a aria-label="Dribble" role="link" href="javascript:void(0)" rel="noopener noreferrer" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-dribbble" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#718096" fill="none" stroke-linecap="round"
                    stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" />
                    <circle cx="12" cy="12" r="9" />
                    <path d="M9 3.6c5 6 7 10.5 7.5 16.2" />
                    <path d="M6.4 19c3.5-3.5 6-6.5 14.5-6.4" />
                    <path d="M3.1 10.75c5 0 9.814-.38 15.314-5" />
                  </svg>
                </a>
              </div>
              <div class="hover:bg-gray-100 hover:bg-opacity-10 p-1 rounded-md">
                <a aria-label="Github" role="link" href="https://github.com/cbedroid" target="_blank" rel="noopener noreferrer">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#718096" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-github">
                    <path
                      d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22">
                    </path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="xl:flex flex-wrap justify-between xl:mt-24 mt-16 pb-6 pl-3 sm:pl-0">
          <div class="w-11/12 xl:w-2/6 mx-auto lg:mx-0 xl:mx-0 mb-6 lg:mb-0 xl:mb-0  pb-4 md:pb-1 md:order-2">
            <ul class="xl:flex lg:flex md:flex sm:flex space-x-5">
              <li class="text-gray-200 hover:text-gray-300 text-base mb-4 sm:mb-0">
                <a class="focus:outline-none focus:underline" href="{% url 'core:terms-conditions' %}">Terms of service</a>
              </li>
              <li class="text-gray-200 hover:text-gray-300 text-base mb-4 sm:mb-0">
                <a class="focus:outline-none focus:underline" href="{% url 'core:privacy-policy' %}">Privacy Policy</a>
              </li>
            </ul>
          </div>
          <div class="w-11/12 xl:w-2/6 mx-auto lg:mx-0 xl:mx-0 mb-6 xl:mb-0">
            <p tabindex="0" class="focus:outline-none text-gray-200 text-base md:order-1 text-center">2022 CMB Technologies and Consulting LLC. All Rights Reserved</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

django/templates/snippets/navigation.html
{% load static %}
<div id="site-navigation">
  <div class="navbar flex shadow-lg bg-neutral text-neutral-content">
    <!-- nav left-->
    <div class="nav nav--left flex-1">

      <div class="flex-none">
        <label for="aside_checkbox">
          <span class="btn btn-square btn-ghost">
            <svg class="inline-block toggler toggler-bar w-6 h-6 stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
            <svg class="hidden toggler toggler-times w-6 h-6 stroke-current" viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <line x1="18" y1="6" x2="6" y2="18"></line>
              <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
          </span>
        </label>
      </div>
      <div class="nav-brand text-lg font-bold">
        <a class="nav__brand-title hidden sm:flex place-items-center " href="{% url 'core:index' %}">
          <img id="site-logo" src="{% static 'assets/images/PhotoShare-logo.png' %}" alt="Photo Share logo">
          <span class=" hidden lg:inline lg:text-2xl font-extrabold text__accent">PhotoShare</span>
        </a>
      </div>
    </div>
    {% if request.user.is_authenticated %}
    <!-- nav middle -->
    <div class="nav nav--middle flex-1 px-5">
      <!-- Search bar -->
      <div class="search-bar w-24  md:w-80 lg:w-full">
        <form class="flex input input-ghost  h-10" action="{% url 'gallery:gallery-list' %}">
          <div class="form-control  flex ">
            <button type="submit" class="w-4 h-full inline ">
              <svg class="inline-block text-gray-400 w-4 h-full m-auto align-middle stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
              </svg>
            </button>
          </div>
          <input class="inline-block bg-transparent input-shrink ghost-focus p-0  text-gray-200 focus:text-gray-100" type="text" name="q" placeholder="Search for free photos" aria-label="search bar">
        </form>
      </div>
    </div>
    <!-- end search bar -->
    {% endif %}

    <!-- Navbar right-->
    <div class="nav nav--right flex-1 place-content-end">
      <div class="hidden  md:flex px-2 mx-2 navbar-center">
        <div class="flex items-stretch">
          <a class="btn btn-ghost btn-sm rounded-btn" href="{% url 'core:index' %}">Home</a>
          <a href={% url 'gallery:gallery-list' %} class="btn btn-ghost btn-sm rounded-btn">Gallery</a>
          {% if not request.user.is_authenticated %}
          <a class="btn btn-ghost btn-sm rounded-btn">About</a>
          <a class="btn btn-ghost btn-sm rounded-btn">Contact</a>
          {% endif %}
        </div>
      </div>
      {% if request.user.is_authenticated %}
      <!-- nav cta -->
      <div class="flex-none">
        <a class="btn btn-square btn-ghost" href="{% url 'gallery:gallery-create' %}">
          <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="10"></circle>
            <line x1="12" y1="8" x2="12" y2="16"></line>
            <line x1="8" y1="12" x2="16" y2="12"></line>
          </svg>
        </a>
      </div>
      <!-- nav noti bell-->
      <div class="flex-none">
        <button class="btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
          </svg>
        </button>
      </div>
      <!---->
      <!-- nav account -->
      <div class="flex-none pr-2">
        <div class=" avatar dropdown dropdown-left">
          <div class="rounded-full w-10 h-10 m-1" tabindex="0">
            <img src="{{request.user.get_profile_pic}}" alt="user avatar">
          </div>
          <ul tabindex="0" class="p-2 shadow menu dropdown-content top-10 bg-base-100 text-gray-200 font-semibold rounded-box w-52" style="top:50px;right:20px">
            <li>
              <a class="text-sm" href="{{request.user.get_update_url}}">
                <svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                  <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                  <circle cx="12" cy="7" r="4"></circle>
                </svg>
                <span class="ml-1">Update Account</span>
              </a>
            </li>
            <li>
              <a class="text-sm" href="{%url 'account_logout'%}">
                <svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1">
                  <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                  <polyline points="16 17 21 12 16 7"></polyline>
                  <line x1="21" y1="12" x2="9" y2="12"></line>
                </svg>
                <span class="ml-1">Logout</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
      {% else %}
      <a class="btn bg-gradient-to-r from-yellow-400  to-[#FF6E0A]" href="{% url 'account_login' %}">
        <span class="animate-bounce rounded-full font-bold  w-2 h-2 bg-purple-400 mr-2"></span>
        Get Started
      </a>
      {% endif %}
    </div>
    <!-- -->
  </div>
</div>