django/core/api/urls.py
from django.urls import re_path
from rest_framework import routers
from rest_framework.authtoken import views as token_views

from . import views

app_name = "api"
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r"user", views.UserViewSet)
router.register(r"gallery", views.GalleryViewSet)
router.register(r"photo", views.PhotoViewSet)

urlpatterns = router.urls
urlpatterns += [
    re_path("^api-token-auth/$", token_views.obtain_auth_token),
]

django/core/urls.py
from django.urls import re_path

from . import views

app_name = "core"
urlpatterns = [
    re_path(r"^terms-conditions/$", views.TermsConditionsView.as_view(), name="terms-conditions"),
    re_path(r"^privacy-policy/$", views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    re_path(r"^contact-us/$", views.ContactUsView.as_view(), name="contact-us"),
    re_path(r"^about-us/$", views.AboutUsView.as_view(), name="about-us"),
    re_path(r"^faqs/$", views.FAQView.as_view(), name="faqs"),
    re_path("", views.HomeView.as_view(), name="index"),
]

django/gallery/urls.py
from django.urls import re_path

from . import views

app_name = "gallery"
# fmt: off
urlpatterns = [
    re_path(r"^delete/(?P<slug>.*)/$", views.GalleryDeleteView.as_view(), name="gallery-delete"),
    re_path(r"^detail/(?P<slug>.*)/$", views.GalleryDetailView.as_view(), name="gallery-detail"),
    re_path(r"^update/(?P<slug>.*)/$", views.GalleryUpdateView.as_view(), name="gallery-update"),
    re_path(r"^collections/$", views.GalleryListView.as_view(), name="gallery-list"),
    re_path(r"^new/$", views.GalleryCreateView.as_view(), name="gallery-create"),
    re_path(r"^photo/detail/(?P<slug>.*)/$", views.PhotoDetailView.as_view(), name="photo-detail"),
    re_path(r"^photo/delete/(?P<slug>.*)/$", views.PhotoDeleteView.as_view(), name="photo-delete"),
    re_path(r"^photo/update/(?P<slug>.*)/$", views.PhotoUpdateView.as_view(), name="photo-update"),
    re_path(r"^photo/update-cover/(?P<pk>\d+)/$", views.photo_cover_update, name="photo-cover-update"),
    re_path(r"^photo/transfer/(?P<pk>\d+)/$", views.photo_transfer, name="photo-transfer"),
    re_path(r"^category/(?P<slug>.*)/$", views.CategoryDetailView.as_view(), name="category-detail"),
]
# fmt: on

django/photoshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(r"^api/", include("core.api.urls")),
    re_path(r"^account/", include("allauth.urls")),
    re_path(r"^account/", include("users.urls")),
    re_path(r"^gallery/", include("gallery.urls")),
    re_path(r"", include("core.urls")),
]


# DEBUG TOOLBAR
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.insert(0, re_path("__debug__/", include(debug_toolbar.urls)))

django/core/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from django.utils.translation import gettext_lazy as _
from simple_history import register


class FAQTopic(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.name


class FAQ(models.Model):
    """Frequently Asked Question"""

    topic = models.ForeignKey(FAQTopic, null=True, on_delete=DO_NOTHING)

    question = models.CharField(
        max_length=150, blank=False, help_text=_("Frequently asked question (150 max char) required")
    )
    answer = models.TextField(
        max_length=500, blank=False, help_text=_("Frequently asked question's answer (500 max char) required")
    )

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = "FAQ"
        verbose_name_plural = "FAQS"


# ********************************#
# ---TRACK CHANGES IN MODELS ---- #
# ********************************#
register(FAQ)

django/gallery/models.py
import re

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models
from django.db.models import Q
from django.templatetags.static import static
from django.urls import reverse
from django.utils.text import slugify
from PIL import Image
from rest_framework.reverse import reverse as api_reverse

from .managers import GalleryManager

User = get_user_model()


class Category(models.Model):

    CATEGORY_LIST = (
        (0, "general"),
        (1, "abstract"),
        (2, "adventure"),
        (3, "architectural"),
        (4, "art"),
        (5, "black and white"),
        (6, "business"),
        (7, "candid"),
        (8, "cityscape"),
        (9, "commercial"),
        (10, "composite"),
        (11, "creative"),
        (12, "documentary"),
        (13, "drone"),
        (14, "double-exposure"),
        (15, "editorial"),
        (16, "event"),
        (17, "family"),
        (18, "fashion"),
        (19, "film"),
        (20, "fine art"),
        (21, "food"),
        (22, "golden hour"),
        (23, "holiday"),
        (24, "indoor"),
        (25, "infrared"),
        (26, "landscape"),
        (27, "lifestyle"),
        (28, "long exposure"),
        (29, "musical"),
        (30, "milky way"),
        (31, "minimalist"),
        (32, "newborn"),
        (33, "night"),
        (34, "pet"),
        (35, "portrait"),
        (36, "product"),
        (37, "real estate"),
        (38, "seascape"),
        (39, "social media"),
        (40, "sports"),
        (41, "still-life"),
        (42, "surreal"),
        (43, "street"),
        (44, "time-lapse"),
        (45, "travel"),
        (46, "underwater"),
        (47, "urban exploration"),
        (48, "war"),
        (49, "wedding"),
        (50, "wildlife"),
    )
    CATEGORY_LABEL = (
        ("bgc-blue text-white", "blue & white"),
        ("bgc-black text-white", "black & white"),
        ("bgc-grey text-white", "grey & white"),
        ("bgc-green text-dark", "green & black"),
        ("bgc-yellow text-dark", "yellow & black"),
        ("bgc-red text-white", "red & white"),
        ("bgc-cyan text-white", "light blue & white"),
        ("bgc-orange text-white", "orange & white"),
        ("bgc-brown text-white", "brown & white"),
        ("bgc-lt-brown text-white", "white brown & white"),
        ("bgc-pink text-white", "pink & white"),
        ("bgc-purple text-white", "purple & white"),
    )
    name = models.IntegerField(choices=CATEGORY_LIST, default=0, unique=True, db_index=True)
    label = models.CharField(max_length=80, choices=CATEGORY_LABEL, default="bgc-black text-white")
    slug = models.SlugField(blank=False, editable=False, db_index=True)

    class Meta:
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.get_name_display())
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("gallery:gallery-list") + f"?q={self.slug}"

    @classmethod
    def choicefield_filter(cls, lookup):
        """Perform lookup on Category by either it's label or display label"""
        lookup = str(lookup)
        # reverse category label to its display label
        display_labels = dict(map(reversed, Category.CATEGORY_LIST))
        label = display_labels.get(lookup)
        if not lookup.isnumeric():
            lookup = None
        return cls.objects.filter(Q(name=label) | Q(name=lookup))

    def __str__(self):
        return self.get_name_display()


class Tag(models.Model):
    """Hash Tags"""

    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name or "Tags"


class Gallery(models.Model):
    objects = GalleryManager()
    name = models.CharField(max_length=75, validators=[MinLengthValidator(3)])
    user = models.ForeignKey(User, related_name="gallery", on_delete=models.CASCADE)
    public = models.BooleanField(default=True)
    category = models.ForeignKey(
        Category,
        related_name="gallery",
        null=True,
        on_delete=models.SET_NULL,
        db_index=True,
    )
    slug = models.SlugField(editable=False, db_index=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    REQUIRED_FIELDS = ["name"]

    class Meta:
        ordering = ["-created"]
        unique_together = ["name", "user"]
        verbose_name_plural = "Galleries"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def cover_photo(self):
        if self.photos:
            cover = self.photos.filter(is_cover=True)
            if cover.exists():
                return cover.first().image.url
        return static("assets/defaults/default_image.jpg")

    def get_absolute_url(self):
        return reverse("gallery:gallery-detail", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("gallery:gallery-update", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("gallery:gallery-delete", kwargs={"slug": self.slug})

    def get_api_url(self, request=None):
        return api_reverse("api:gallery-detail", kwargs={"pk": self.pk}, request=request)

    def __str__(self):
        return self.name


class Photo(models.Model):
    title = models.CharField(max_length=80, validators=[MinLengthValidator(3)])
    image = models.ImageField(upload_to="gallery")
    gallery = models.ForeignKey(
        Gallery,
        related_name="photos",
        blank=True,
        db_index=True,
        on_delete=models.CASCADE,
    )
    is_cover = models.BooleanField(default=False)
    views = models.PositiveIntegerField(default=0)
    downloads = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField(Tag, blank=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    slug = models.SlugField(blank=False, editable=False, db_index=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("gallery:photo-detail", kwargs={"slug": self.slug})

    def get_update_url(self):
        return reverse("gallery:photo-update", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("gallery:photo-delete", kwargs={"slug": self.slug})

    def get_download_title(self):
        """Creates filename for download from photo title"""
        user = self.gallery.user
        app_name = settings.ROOT_URLCONF.split(".")[0].title()
        photo = re.sub(" ", "_", str(self))
        return f"{app_name}_{photo}_by_{user}.jpg"

    def mime_type(self):
        image = Image.open(self.image.path)
        return image.get_format_mimetype() or "unknown"

    def dimension(self):
        return f"{self.image.height} X {self.image.width}"

    def total_likes(self):
        return self.rate_set.like.filter(like=True).count()

    def total_stars(self):
        return self.rate_set.like.filter(star=True).count()


class Rate(models.Model):
    like = models.BooleanField(default=False)
    star = models.BooleanField(default=False)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} {self.photo.title} - Like: {int(self.like)} Star: {int(self.star)}"

django/core/forms.py
from django import forms


class ContactUsForm(forms.Form):
    MESSAGE_PLACEHOLDER = "How Can We Help You?"
    NAME_PLACEHOLDER = "Your Name"
    EMAIL_PLACEHOLDER = "Your Email"

    name = forms.CharField(
        required=True,
        max_length=120,
        widget=forms.TextInput(attrs={"class": "cf-name", "placeholder": NAME_PLACEHOLDER}),
    )

    email = forms.EmailField(
        required=True,
        max_length=80,
        widget=forms.TextInput(
            attrs={
                "class": "cf-email",
                "placeholder": EMAIL_PLACEHOLDER,
            }
        ),
    )
    message = forms.CharField(
        required=True,
        max_length=500,
        widget=forms.Textarea(
            attrs={"rows": "6", "cols": "40", "class": "cf-message", "placeholder": MESSAGE_PLACEHOLDER}
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # remove annoying autofocus
        for field in self.fields:
            try:
                field.widget.attrs.pop("autofocus", None)
            except BaseException:
                pass

django/core/api/views.py
from allauth.account.models import EmailAddress
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models import Q
from gallery.models import Gallery, Photo
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import AllowAny
from rest_framework.viewsets import ModelViewSet

from .permissions import IsAuthOrStaff, IsOwnerOrReadOnly
from .serializers import GallerySerializer, PhotoSerializer, UserSerializer

User = get_user_model()


class UserViewSet(ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_permissions(self):
        if self.request.method == "POST":
            self.permission_classes = (AllowAny,)
        return super(UserViewSet, self).get_permissions()

    def perform_create(self, serializer):
        user = serializer.save()
        if settings.ACCOUNT_EMAIL_VERIFICATION.lower() != "none":
            email = EmailAddress.objects.create(user=user, email=user.email)
            email.send_confirmation()
        return user


class GalleryViewSet(ModelViewSet):
    queryset = Gallery.objects.all()
    serializer_class = GallerySerializer
    permission_classes = [IsOwnerOrReadOnly, IsAuthOrStaff]

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            # Query Gallery album based on its public status.
            # If the gallery belongs to the logged in, disregard "public" state
            # include his/her private galleries as well.
            return Gallery.objects.filter(Q(public=True) | Q(user=user))
        return Gallery.objects.filter(public=True)

    def get_object(self):
        # NOTE: Added get_object permission to here to alter HTTP response.
        #      Changed status 403 to 404 to hide that the gallery even exists.
        #      This can help protect against hackers by disgusing that gallery is not found.
        #
        obj = get_object_or_404(self.get_queryset(), pk=self.kwargs["pk"])
        self.check_object_permissions(self.request, obj)
        return obj

    def get_serializer_context(self, **kwargs):
        context = super().get_serializer_context(**kwargs)
        context["user"] = self.request.user
        context["request"] = self.request
        return context

    def perform_create(self, serializer):
        return serializer.save(user=self.request.user)

    def perform_update(self, serializer):
        return serializer.save(user=self.request.user)


class PhotoViewSet(ModelViewSet):
    queryset = Photo.objects.all()
    serializer_class = PhotoSerializer

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            # Query Gallery album based on its public status.
            # If the gallery belongs to the logged in, disregard "public" state
            # include his/her private galleries as well.
            return Photo.objects.filter(Q(gallery__public=True) | Q(gallery__user=user))
        return Photo.objects.filter(gallery__public=True)

    def perform_destroy(self, instance):
        instance.delete()
        # Delete related gallery if it is now empty
        photo_count = instance.gallery.photos.count()
        if photo_count == 0:
            instance.gallery.delete()

django/core/templates/core/gallery_confirm_delete.html
{% extends "core/base.html" %}
{% block body %}

<section id="gallery-deletion" class="clear-top bg-gray-50 h-screen">
  <div class="content-section p-2 px-4">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group p-2">
        <legend class="content__title content-title mb-4">
          <i class="fa fa-photo sm:text-3xl"></i>
          Delete Gallery
        </legend>
        <hr>
        <div class="confirmation-text text-2xl font-semibold font-serif text-gray-500 text-opacity-75 mt-4">
          <h2>Are you sure you want to delete this gallery? </h2>
          <h4>
            <span>&ldquo;</span>
            <span class="text-red-500 text-shadow">{{object}}</span>
            <span>&rdquo;</span>
          </h4>
        </div>
          <div class="action-btn-group mt-4">
            <button class="cta cta--outline-red" type="submit">Yes, Delete</button>
            <a class="cta cta--outline-grey" href="{{object.get_absolute_url}}">Cancel</a>
        </div>
      </fieldset>
    </form>
  </div>
</section>
{% endblock body %}

django/core/templates/core/gallery_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load core_extras %}
{% load social_share %}


{% block body %}
<section id="gallery-section" class="theme-ws clear top mx-2 pb-2">
  <!-- Gallery Header-->
  <div class="header p-6 space-y-6">
    <div class="header__title flex-between">
      <div class="header__content header__content--left">
        <h4 class="pb-1 text-2xl"><b>{{gallery}}</b></h4>
        <p class="pb-1">
          <i class="fas fa-user-circle"></i>
          {{gallery.user}}
        </p>
      </div>
      <div class="header__content header__content--right">
        <div class="header__action text-2xl text-gray-400">
          <a href="#" class="border-2 border-gray-200 p-2 px-4 hover:text-red-600 mr-1">
            <i class="fa fa-heart"></i>
          </a>
          <a href="#" class="border-2 border-gray-200 p-2 px-4 hover:text-blue-300">
            <i class="text-3xl fa fa-share-square"></i>
          </a>
        </div>
      </div>
    </div>

    <!-- header user__actions -->
    <div class="user__action flex-between mt-2 w-100">
      <h4><span class="badge rounded-full py-2 px-4 hover:text-black hover: {{gallery.category.get_label_display}}">{{gallery.category.get_name_display|title}}</span></h4>
      {% if request.user == gallery.user %}
      <div class=action__btn>
        <a href="{% url 'core:gallery-update' gallery.user.username|slugify gallery.slug %}" class="cta cta--outline-blue badge">update
          <span class="hidden sm:inline-block">gallery </span>
        </a>
        <span class="spacer mx-1"> </span>
        <a href="{% url 'core:gallery-delete' gallery.user.username|slugify gallery.slug %}" class="cta cta--outline-red badge">delete
          <span class="hidden sm:inline-block">gallery </span>
        </a>
      </div>
      {% endif %}
    </div>
  </div>
  <!-- -->
  <hr>

  <!-- Photo Collections -->
  <div id="photo-collection" class="px-1 sm:px-2">
    <div class="container p-1 sm:p-6">
      <div class="row wrapper">
        <ul id="gallery-photo-collections" class="photo grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2 sm:gap-3 lg:gap-4">
          {% for photo in photo_set %}
          <li class="photo__card py-1 shadow-lg hover:shadow-2xl">
            <h4 class="photo__title py-1 text-center text-ellipsis text-sm sm:text-base font-semibold font-serif">{{photo.title}}</h4>
            <!-- Photo Image-->
            <div class="photo__image">
              <a href="{{photo.get_absolute_url}}">
                <img class="img-fluid" src="{{photo.image.url}}" alt="{{photo.gallery}} {{photo}} photo">
              </a>
            </div>
            <!-- -->
            <!-- Photo Details -->
            <div class="detail flex flex-col sm:flex-row -between sm:space-x-1 w-100 p-1">
              <small class="detail__date w-50 sm:flex-1 sm:text-left">
                <i class="fa fa-clock mr-1"></i>
                {{photo.created|date:"M d, Y"}}
              </small>
              <small class="detail__user text-ellipsis nowrap sm:text-right sm:flex-1" style="max-width:calc(100% / 2);">
                <i class="fa fa-user mr-1"></i>
                <span class="text-truncated">{{gallery.user}}</span>
              </small>
            </div>
            <!-- -->
            <!--Photo share-->
            <div class="share__hidden hidden row align-content-center">
              <div class="social-share py-2">
                <div class="social-share__content bg-white shadow-lg">
                  <div class="share-grid grid grid-cols-12 gap-4 my-1 sm:p-1">
                    <div class="social-share__img-wrapper col-start-1 col-span-12 flex-center">
                      <img src="{{photo.image.url}}" class="social-share__img">
                    </div>
                    <div class="share-card col-start-1 col-span-12">
                      <div class="share-card__content py-2">
                        <h4 class="text-3xl font-semibold">{{photo}}</h4>
                        <p class="text-muted font-italic">created by: <i class="fa fa-user-circle mx-1"></i>{{photo.gallery.user}}</p>
                      </div>
                      <!-- Social media links-->
                      <div class="link col-start-6 col-span-6 my-4 border-2 border-grey-200 py-4">
                        <p class="text-center">Share it on your social media.</p>
                        <div class="share-card__link flex flex-row space-x-4 justify-center w-100 mt-2">
                          {% post_to_twitter 'Post your amazing photo using Photo-Share' photo.image.url '<i class="fa fa-twitter share__icon bg-blue-600"><p>Twitter</p></i>'%}
                          {% post_to_facebook photo.image.url '<i class="fa fa-facebook share__icon bg-blue-600"><p>Facebook</p></i>' %}
                          {% post_to_gplus photo.image.url '<i class="fab fa-google-plus-square share__icon bg-red-600"><p>Google &#43;</p></i>'%}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- -->
            <!--Photo share action-->
            <div class="clear-both"></div>
            <div class="share-action flex-between space-x-1 relative bottom-0 left-0">
              {% if request.user.is_authenticated and request.user == gallery.user %}
              <a class="cta cta--red cta--full-block" href="{% url 'core:photo-delete' photo.pk %}">
                <i class="fas fa-trash"></i>
              </a>
              {% else %}
              <a class="cta cta--red cta--full-block" href="#">
                <i class="fas fa-heart"></i>
              </a>
              {% endif %}

              <a class="cta cta--blue cta--full-block share_popup" href="#">
                <i class="fas fa-share-alt"></i>
              </a>
              <a class="cta cta--green cta--full-block" href="#">
                <i class="fas fa-cloud-download-alt"></i>
              </a>
            </div>
            <!-- -->
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <!-- -->

  <section id="related_gallery" class="mt-14">
    <div class="container p-1 sm:p-6">
      <div class="row">
        <h5 class="fw-bold pb-3 text-2xl border-b-2 border-gray-300">Related Gallery</h5>
        <ul class="gallery grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2 sm:gap-3 lg:gap-4 mt-4">
          {% for related in related_gallery %}
          <li class="gallery__card shadow">
            <div class="gallery__content pos-relative">
              <div class="gallery__image image">
                <img class="img-fluid" src="{{gallery.cover_photo.image.url}}" alt="{{gallery}} {{gallery.cover_photo}} photo">
              </div>
              <!-- Gallery Overlay -->
              <div class="image-overlay overlay overlay--bgdark overlay--hovershow text-white">
                <div id="index-grid-overlay" class="overlay__content grid grid-flow-rows h-100 p-2">
                  <div class="flex-evenly flex-wrap text-xs sm:text-base mx-1 overflow-hidden">
                    <a class="text-ellipsis" href="{{related.get_absolute_url}}"><b>{{related}}</b></a>
                    <h6 class="mt-1"><span class="badge rounded-full {{related.category.get_label_display}} p-1">{{related.category.get_name_display}}</span></h6>
                  </div>
                  <div class="flex-center text-xs sm:text-base mx-1 overflow-hidden">
                    <a class="text-shadow p-3" href="{{related.get_absolute_url}}"><b>view gallery</b></a>
                  </div>
                  <div class="flex-evenly flex-wrap text-xs sm:text-base mx-1 overflow-hidden">
                    <p class="">{{related.photo_set.count}}
                      <i class="fas fa-images"></i>
                    </p>
                    <p class="font-italic text-ellipsis"><i class="fa fa-user-circle user__icon mr-1"></i>{{related.user.username}} </p>
                  </div>
                </div>
              </div>
              <!-- Gallery Overlay -->
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </section>
</section>


{% endblock body %}

django/core/templates/core/gallery_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
<section class="gallery-form-section clear-top theme-ws">
  <!-- gallery-->
  {# TODO: Add Aside on the right for large screen. There is too much extra space #}
  <div class="content-container container p-3 pb-5 sm:p-6 w-100">
    <!-- gallery Content Form -->

    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ formset.management_form }}
      <!-- Gallery  Form -->
      <fieldset id="galleryset-form" class="gallery-form space-y-8">
        <legend class="content-title border-bottom mb-4">
          <i class="far fa-images"></i>
          {% if form.instance.id %}
          Update Gallery
          {% else %}
          Create Gallery
          {% endif %}
        </legend>
        <div class="form-group space-y-4 w-100">
          {{ form|crispy }}
        </div>
      </fieldset>
      <!-- End Gallery Form -->

      <!-- Photo Form -->
      <fieldset id="photoset-form" class="mt-2">
        <div class="card-wrapper grid grid-cols-2 space-x-2 max-w-xl">
          {% for gallery_form in formset %}
          <!-- Form {{forloop.counter}}-->
          <div class="photoform__card card bg-white shadow-md">
            <div class="card__body text-center">
              {{gallery_form.title}}
              {% if gallery_form.title.errors %}
              <ul class="title-errors alert-danger">
                {{gallery_form.title.errors|unordered_list}}
              </ul>
              {% endif %}
              {{gallery_form.image.label|safe}}
              {{gallery_form.image}}
              {% if gallery_form.image.errors %}
              <ul class="image-errors alert-danger">
                {{gallery_form.image.errors|unordered_list}}
              </ul>
              {% endif %}
            </div>
          </div>
          <!-- -->
          {% endfor %}
        </div>
      </fieldset>

      <div class="cta--btn-group align-center space-x-3 mt-4">
        {% if form.instance.id %}
        <input class="cta cta--outline-yellow" type="submit" value="Update" style="padding:4px 16px">
        {% else %}
        <input class="cta cta--outline-cyan" type="submit" value="Add" style="padding:4px 16px">
        {% endif %}
        <a class="cta cta--outline-red" href="{% url 'core:index' %}" style="padding:6px 16px">Cancel</a>
      </div>
    </form>
  </div>
  <!--/gallery Content Form -->
  <!-- End gallery-->
</section>
{% endblock body %}