django/core/urls.py
from django.urls import re_path

from . import views

app_name = "core"
urlpatterns = [
    re_path(r"^terms-conditions/$", views.TermsConditionsView.as_view(), name="terms-conditions"),
    re_path(r"^privacy-policy/$", views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    re_path(r"^contact-us/$", views.ContactUsView.as_view(), name="contact-us"),
    re_path(r"^about-us/$", views.AboutUsView.as_view(), name="about-us"),
    re_path(r"^faqs/$", views.FAQView.as_view(), name="faqs"),
    re_path("", views.HomeView.as_view(), name="index"),
]

django/gallery/urls.py
from django.urls import re_path

from . import views

app_name = "gallery"
# fmt: off
urlpatterns = [
    re_path(r"^delete/(?P<slug>.*)/$", views.GalleryDeleteView.as_view(), name="gallery-delete"),
    re_path(r"^detail/(?P<slug>.*)/$", views.GalleryDetailView.as_view(), name="gallery-detail"),
    re_path(r"^update/(?P<slug>.*)/$", views.GalleryUpdateView.as_view(), name="gallery-update"),
    re_path(r"^collections/$", views.GalleryListView.as_view(), name="gallery-list"),
    re_path(r"^new/$", views.GalleryCreateView.as_view(), name="gallery-create"),
    re_path(r"^photo/detail/(?P<slug>.*)/$", views.PhotoDetailView.as_view(), name="photo-detail"),
    re_path(r"^photo/delete/(?P<slug>.*)/$", views.PhotoDeleteView.as_view(), name="photo-delete"),
    re_path(r"^photo/update/(?P<slug>.*)/$", views.PhotoUpdateView.as_view(), name="photo-update"),
    re_path(r"^photo/update-cover/(?P<pk>\d+)/$", views.photo_cover_update, name="photo-cover-update"),
    re_path(r"^photo/transfer/(?P<pk>\d+)/$", views.photo_transfer, name="photo-transfer"),
    re_path(r"^category/(?P<slug>.*)/$", views.CategoryDetailView.as_view(), name="category-detail"),
]
# fmt: on

django/photoshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(r"^api/", include("core.api.urls")),
    re_path(r"^account/", include("allauth.urls")),
    re_path(r"^account/", include("users.urls")),
    re_path(r"^gallery/", include("gallery.urls")),
    re_path(r"", include("core.urls")),
]


# DEBUG TOOLBAR
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.insert(0, re_path("__debug__/", include(debug_toolbar.urls)))

django/core/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from django.utils.translation import gettext_lazy as _
from simple_history import register


class FAQTopic(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.name


class FAQ(models.Model):
    """Frequently Asked Question"""

    topic = models.ForeignKey(FAQTopic, null=True, on_delete=DO_NOTHING)

    question = models.CharField(
        max_length=150, blank=False, help_text=_("Frequently asked question (150 max char) required")
    )
    answer = models.TextField(
        max_length=500, blank=False, help_text=_("Frequently asked question's answer (500 max char) required")
    )

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = "FAQ"
        verbose_name_plural = "FAQS"


# ********************************#
# ---TRACK CHANGES IN MODELS ---- #
# ********************************#
register(FAQ)

django/gallery/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.utils.safestring import mark_safe

from .models import Category, Gallery, Photo


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ["name", "category", "public"]

    name = forms.CharField(
        required=True,
        label="Gallery name",
        widget=forms.TextInput(attrs={"placeholder": "Enter a gallery title"}),
    )
    category = forms.ModelChoiceField(
        label="category",
        empty_label="(Select Category)",
        widget=forms.Select,
        queryset=Category.objects.all(),
        required=True,
    )

    def clean_name(self):
        name = self.cleaned_data.get("name", "")
        name = re.sub(r"\s{1,}", " ", name).strip()

        # If form.instance then the form is being `updated` otherwise `created`.
        gallery_obj = Gallery.objects.filter(name__iexact=name)
        if self.instance:

            # Checking for gallery unique_together on field: `User.id and Gallery.name`
            gallery_obj = gallery_obj.exclude(name=self.instance.name)
        if gallery_obj.exists():
            raise ValidationError("Sorry, This Gallery already exist!")
        return name

    def save(self, commit=True, *args, **kwargs):
        return super(GalleryForm, self).save(commit=commit)


class PhotoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

    IMAGE_PREVIEW = mark_safe(
        """
        <label class="photoset__image_label">
            <p class="image__label text-ellipsis font-bold text-gray-900 text-center py-4">add photo</p>
            <img class="image form-image w-full" src="static/assets/images/add_image.png" style="height:200px;"/>
        </label>"""
    )

    class Meta:
        model = Photo
        fields = "__all__"

    title = forms.CharField(
        required=True,
        label=False,
        widget=forms.TextInput(attrs={"placeholder": "Image title", "class": "photo-form text-center"}),
    )
    image = forms.ImageField(required=True, label=IMAGE_PREVIEW, widget=forms.FileInput)

    def clean_title(self):
        # Gallery unique_together will be force here
        # on fields (<Photo.gallery.user>` and `<Photo.title>`)

        title = self.cleaned_data.get("title")
        if not title:
            raise ValidationError("Sorry, This photo must have a title")

        # NOTE: Only validating photo's title if the form is being updated.
        #       Required fields will be forced only when gallery is being created,
        #       otherwise empty fields can be deemed as valid fields.
        title = re.sub(r"\s{1,}", " ", title).strip()
        photos = Photo.objects.filter(gallery__user=self.user, title=title)
        if photos.exists():
            raise ValidationError("Sorry, That image title is already taken")
        return title


class BaseGalleryFormset(BaseInlineFormSet):
    def clean(self):
        if any(self.errors):
            return

        titles = []
        for form in self.forms:  # <-- formset's forms
            if self.can_delete and self._should_delete_form(form):
                continue

            title = form.cleaned_data.get("title")
            if title:
                titles.append(title)

        # Force Gallery creation to have at least one photo.
        if not self.instance.id and not titles:
            raise ValidationError("At least one photo must be added to your gallery")

    def save(self, commit=True):
        instance = super(BaseGalleryFormset, self).save(commit=False)
        instance.gallery = self.instance
        if commit:
            instance.save()
        return instance


GalleryFormSet = inlineformset_factory(
    Gallery,
    Photo,
    form=PhotoForm,
    formset=BaseGalleryFormset,
    fields=["title", "image", "is_cover"],
    extra=4,
    max_num=20,
)

django/gallery/views.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count, Q, Sum
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.views.generic.list import MultipleObjectMixin

from .mixins import GalleryFormMixin, UserAccessPermissionMixin
from .models import Category, Gallery, Photo


class GalleryDetailView(DetailView, MultipleObjectMixin):
    model = Gallery
    template_name = "gallery/gallery_detail.html"
    object_list = None
    paginate_by = 25

    # Throws 404 if gallery is private
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            return Gallery.objects.filter(Q(public=True) | Q(user=self.request.user))
        else:
            return Gallery.objects.filter(public=True)

    def get_context_data(self, **kwargs):
        obj = self.get_object()
        object_list = obj.photos.order_by("-pk")
        context = super().get_context_data(object_list=object_list, **kwargs)
        related_gallery = self.object.category.gallery
        user = self.request.user
        if related_gallery.exists():
            # Filter galleries by owner or its public state
            # Only display galleries if user is the owner or gallery is public
            if user.is_authenticated:
                related_gallery = related_gallery.filter(
                    Q(public=True) | Q(user=self.request.user),
                ).exclude(pk=self.object.pk)
            else:
                related_gallery = related_gallery.filter(public=True).exclude(pk=self.object.pk)

        context["related_gallery"] = related_gallery[:20]
        context["is_user"] = obj.user == self.request.user
        context["cover_photo"] = obj.photos.filter(is_cover=True).last()
        return context


class GalleryListView(ListView):
    model = Gallery
    template_name = "gallery/gallery_list.html"
    paginate_by = 25

    def get_queryset(self):
        if self.request.user.is_authenticated:
            qs = Gallery.objects.filter(Q(public=True) | Q(user=self.request.user))
        else:
            qs = Gallery.objects.filter(public=True)

        search = self.request.GET.get("q")
        if search:
            return Gallery.objects.query_search(search, qs)

        # TODO order by datetime range  - one to two week newest
        return qs.annotate(photo_views=Sum("photos__views")).order_by("?", "-photo_views")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Show top 20 trending category
        context["by_search"] = self.request.GET.get("q", False)
        context["top_category"] = Category.objects.alias(c=Count("gallery")).order_by("-c")[:20]
        return context


class GalleryCreateView(GalleryFormMixin, CreateView):
    model = Gallery
    login_url = reverse_lazy("account_login")
    template_name = "gallery/gallery_form.html"
    object = None


class GalleryUpdateView(GalleryFormMixin, UserPassesTestMixin, UpdateView):
    model = Gallery
    login_url = reverse_lazy("account_login")
    template_name = "gallery/gallery_form.html"
    object = None

    def test_func(self):
        """Test whether the Gallery belongs to the current user"""
        return self.request.user == self.get_object().user


class GalleryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Gallery
    template_name = "galle(ry/gallery_confirm_delete.html"
    login_url = reverse_lazy("account_login")
    success_url = reverse_lazy("core:index")

    def test_func(self):
        """Test whether the Gallery belongs to the current user"""
        return self.request.user == self.get_object().user


# PHOTO
class PhotoDetailView(UserAccessPermissionMixin, DetailView):
    model = Photo
    template_name = "gallery/photo_detail.html"
    context_object_name = "photo"
    slug_url_kwarg = "slug"

    # Throws 404 if photo gallery is private
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            return Photo.objects.filter(Q(gallery__public=True) | Q(gallery__user=self.request.user))
        else:
            return Photo.objects.filter(gallery__public=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context["is_user"] = obj.gallery.user == self.request.user
        context["galleries"] = Gallery.objects.filter(user=obj.gallery.user).exclude(pk=obj.gallery.pk)
        return context

    def get(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.views += 1
        self.object.save()
        context = self.get_context_data()
        return self.render_to_response(context)


class PhotoDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Photo
    template_name = "gallery/photo_confirm_delete.html"

    def test_func(self):
        """Test whether the Photo belongs to the current user"""
        user = self.get_object().gallery.user
        return user == self.request.user

    def get_success_url(self, *args, **kwargs):
        gallery = self.object.gallery
        if gallery.photos.count() > 1:
            return gallery.get_absolute_url()
        return reverse("core:index")

    def post(self, *args, **kwargs):
        response = super().post(*args, **kwargs)
        gallery = self.object.gallery
        if gallery.photos.count() == 0:
            gallery.delete()
            messages.warning(
                self.request,
                "".join(
                    (
                        f'Your gallery "{gallery}" was deleted,',
                        " because it does not contain any photos",
                    )
                ),
            )
        return response


class PhotoUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Photo
    login_url = "account_login"

    def test_func(self):
        """Test whether the Photo belongs to the current user"""
        user = self.get_object().gallery.user
        return user == self.request.user

    def post(self, *args, **kwargs):
        if self.request.is_ajax():
            response = {"status": False}
            obj = self.get_object()
            data = json.loads(self.request.body)
            obj.is_cover = data.get("cover")
            obj.save()
            response["status"] = True
            return JsonResponse(response)
        super().post(*args, **kwargs)


def photo_cover_update(request, pk=None):
    obj = get_object_or_404(Photo, pk=pk)
    owner = obj.gallery.user

    if request.user == owner and request.method == "POST":
        if request.is_ajax():
            response = {"status": False}
            data = json.loads(request.body)
            obj.is_cover = data.get("cover")
            obj.save()
            response["status"] = True
            return JsonResponse(response)
    return redirect(".")


def photo_transfer(request, pk=None):
    data = dict(request.POST)

    obj = Photo.objects.get(pk=pk)
    gallery = Gallery.objects.get(pk=data["gallery"][0])
    obj.gallery = gallery
    obj.save()
    return redirect(obj.gallery.get_absolute_url())  # core:index")


class CategoryDetailView(DetailView):
    slug_url_kwarg = "slug"
    pass

django/templates/gallery/snippets/gallery_cards.html
<section id="gallery-collection" class="gallery-card-deck my-5 py-5">
  <ul class="gallery-list grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-4 xxl:grid-cols-8 gap-4 sm:gap-3 lg:gap-4">
    {% for gallery in galleries %}
    <li class="gallery__card  relative shadow" style="height:300px;max-width:500px;">
      <!--card image overlay -->
      <img class="block rounded-lg w-full h-full p-0" src="{{gallery.cover_photo}}" alt="{{gallery}} {{gallery.cover_photo}}">
      <div class="image-overlay absolute rounded-lg top-0 left-0 overlay--bgdark overlay--hovershow text-white w-full h-full">
        <div class="overlay__content grid grid-flow-rows w-fit p-2">
          <div class="flex-evenly flex-wrap text-xs sm:text-base mx-1 overflow-hidden">
            <a class="text-ellipsis" href="{{gallery.get_absolute_url}}"><b>{{gallery}}</b></a>
            <h6 class="mt-1"><span class="badge badge--pill rounded-full {{gallery.category.label}} p-2">{{gallery.category.get_name_display}}</span></h6>
          </div>
          <div class="flex-center text-xs sm:text-base mx-1 overflow-hidden">
            <a class="text-shadow p-3" href="{{gallery.get_absolute_url}}"><b>view gallery</b></a>
          </div>
          <div class="flex-box flex-evenly flex-wrap text-xs sm:text-base mx-1 overflow-hidden">
            <div class="flex-box--left flex place-items-center space-x-2">
              <span>{{gallery.photos.count}}</span>
              <i class="fas fa-images"></i>
            </div>
            <div class="flex-box--right flex place-items-center space-x-2 font-italic text-ellipsis">
              <img class="inline rounded-full w-6 h-6" src="{{gallery.user.get_profile_pic}}" alt="user">
              <span class="font-semibold">
                {{gallery.user.username}}
              </span>
            </div>
          </div>
        </div>
        <!-- -->
      </div>
    </li>
    {% endfor %}
  </ul>
  {% if not galleries %}
  <div class="mx-auto">
    <div class="content-empty text-center px-1 max-w-full">
      <h1 class="font-bold text-3xl">No gallery found {% if by_search %}for <span class="mt-2 text-gray-400">"{{ by_search }}"</span>{% endif %}</h1>
      {% if not object %}
      <p class="my-3">Be the first to create this gallery</p>
      {% else %}
      <p class="my-3">Create a related gallery for this category</p>
      {% endif %}
      <div class="block w-56 mt-4">
        <a class="btn  btn-warning  border-yellow-400 text-yellow-400 bg-transparent px-5 shadow-lg  hover:text-white  hover:border-yellow-400 hover:bg-yellow-400 duration-300"
          href="{% url 'gallery:gallery-create' %}">Create Gallery
        </a>
      </div>
    </div>
  </div>
  {% endif %}
</section>

django/templates/gallery/snippets/gallery_delete_modal.html
<!-- This example requires Tailwind CSS v2.0+ -->
<div id="gallery_delete_modal" class="fixed z-10 inset-0 overflow-y-auto hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
      <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
        <div class="sm:flex sm:items-start">
          <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
            <!-- Heroicon name: outline/exclamation -->
            <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
            <h3 class="text-lg leading-6 font-bold text-gray-900" id="modal-title">
              Delete Gallery
            </h3>
            <div class="mt-2">
              <div class="wrapper text-gray-500">
                <p class="text-lg text-gray-500">
                  <span>Are you sure you want to delete?</span>
                  <span class="block text-xl font-bold ml-2">{{object}}</span>
                </p>
                <div class="bg-yellow-100 rounded-md mt-3 p-2 px-3">
                  <p>All of your photos related to this gallery will also be permanently removed.</p>
                  <div class="mt-2">
                    <i class="fa fa-exclamation-triangle"></i>
                    <span>This action cannot be undone.</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
        <form id="gallery_modal_form" action="{{object.get_delete_url}}" method="POST">
          {% csrf_token %}
          <input id="form_submit" type="submit"
            class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm"
            value="Delete">
          <input id="form_cancel" type="button"
            class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
            value="Cancel">
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(() => {
    const modal = $('#gallery_delete_modal');
    const form = $(modal).find('form');
    const modal_trigger = $('[data-target="gallery-delete-modal"]');

    // Bind modal actions events
    $(form).find('#form_cancel').bind('click', (e) => {
      e.preventDefault();
      $(modal).addClass('hidden');
    })
    // Bind modal trigger events
    $(modal_trigger).bind('click', function (e) {
      e.preventDefault();
      $(modal).removeClass('hidden');
    });

  })
</script>

django/templates/gallery/snippets/photo_transfer_modal.html
<div id="photo_transfer_modal" class="fixed z-10 inset-0 overflow-y-auto hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <form id="photo_modal_form" action="{% url 'gallery:photo-transfer' pk=object.pk %}" method="POST">
    {% csrf_token %}
    <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>
      <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
      <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
        <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
          <div class="sm:flex sm:items-start">
            <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-blue-100 sm:mx-0 sm:h-10 sm:w-10">
              <!-- Heroicon name: outline/exclamation -->
              <svg class="h-6 w-6 text-blue-600" x viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                <polyline points="16 17 21 12 16 7"></polyline>
                <line x1="21" y1="12" x2="9" y2="12"></line>
              </svg>
            </div>
            <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
              <h3 class="text-lg leading-6 font-bold text-gray-900" id="modal-title">
                Transfer Photo
              </h3>
              <div class="mt-2">
                <p class="text-lg text-gray-500">
                  <span>Transfer <b>{{object}}</b> photo to another gallery?</span>
                </p>
                <div class="wrapper text-gray-500 mt-6">
                  <label class="block text-gray-800 font-semibold mb-1" for="gallery-select">select a gallery</label>
                  <select name="gallery" id="gallery-select">
                    {% for gallery in galleries  %}
                    <option value="{{gallery.pk}}">{{gallery}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex">
          <input id="form_submit" type="submit"
            class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-3 py-2 bg-blue-600 text-base font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:ml-3 sm:w-auto sm:text-sm"
            value="transfer">
          <input id="form_cancel" type="button"
            class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-3 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
            value="Cancel">
        </div>
      </div>
    </div>
  </form>
</div>
<script>
  $(document).ready(() => {
    const modal = $('#photo_transfer_modal');
    const form = $(modal).find('form');
    const modal_trigger = $('[data-target="photo-transfer-modal"]');

    // Bind modal actions events
    $(form).find('#form_cancel').bind('click', (e) => {
      e.preventDefault();
      $(modal).addClass('hidden');
    })
    // Bind modal trigger events
    $(modal_trigger).bind('click', function (e) {
      e.preventDefault();
      $(modal).removeClass('hidden');
    });

  })
</script>

django/templates/gallery/snippets/social-share.html
{% load static  social_share %}

{# Must be include with 'photo' variable #}

<!--Photo share Modal-->
<div class="photoshare-social-share share__hidden hidden row align-content-center">
  <div class="social-share py-2">
    <div class="social-share__content bg-white shadow-sm">
      <div class="share-grid grid grid-cols-12 gap-4 my-1 sm:p-1">
        <div class="social-share__img-wrapper col-start-1 col-span-12 flex-center">
          <img src="{{photo.image.url}}" class="social-share__img" alt="{{photo.title}}">
        </div>
        <div class="share-card col-start-1 col-span-12">
          <div class="share-card__content py-2">
            <h4 class="text-3xl font-semibold">{{photo}}</h4>
            <p class="text-muted font-italic">created by: <i class="fa fa-user-circle mx-1"></i>{{photo.gallery.user}}</p>
          </div>
          <!-- Social media links-->
          <div class="link col-start-6 col-span-6 my-4 border-2 border-grey-200 no-underline rounded-md py-4 px-2">
            <h4 class="text-center">Share this on your social media.</h4>
            <div class="flex flex-row space-x-4 justify-center mt-2">
              {% post_to_facebook photo.image.url '<div class="flex place-content-center place-items-center gap-x-3 group drop-shadow-md duration-300 p-1 bg-white text-gray-400 border border-gray-200  hover:border-gray-400 rounded-sm h-15"><i class="fab fa-facebook-f font-sm bg-[#1877f2] text-white rounded-full p-2"></i><p class="text-sm group-hover:text-gray-700 ml-4">Facebook</p></div>' link_class='social-link' %}
              {% post_to_twitter 'Post your amazing photo using Photo-Share' photo.image.url '<div class="flex place-content-center place-items-center gap-x-3 group drop-shadow-md duration-300 p-1 bg-white text-gray-400 border border-gray-200  hover:border-gray-400 rounded-sm h-15"><i class="fab fa-twitter font-sm bg-[#1da1f2] text-white rounded-full p-2"></i><p class="text-sm group-hover:text-gray-700 ml-4">Twitter</p></div>' link_class='social-link' %}
              {% post_to_gplus photo.image.url '<div class="flex place-content-center place-items-center gap-x-3 group drop-shadow-md  duration-300 p-1 bg-white text-gray-400 border border-gray-200  hover:border-gray-400 rounded-sm h-15"><i class="fab fa-google-plus font-sm bg-[#ea4335] text-white rounded-full p-2"></i><p class="text-sm group-hover:text-gray-700 ml-4">Google &#43;</p></div>' link_class='social-link' %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- -->