django/core/urls.py
from django.urls import re_path

from . import views

app_name = "core"
urlpatterns = [
    re_path(r"^terms-conditions/$", views.TermsConditionsView.as_view(), name="terms-conditions"),
    re_path(r"^privacy-policy/$", views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    re_path(r"^contact-us/$", views.ContactUsView.as_view(), name="contact-us"),
    re_path(r"^about-us/$", views.AboutUsView.as_view(), name="about-us"),
    re_path(r"^faqs/$", views.FAQView.as_view(), name="faqs"),
    re_path("", views.HomeView.as_view(), name="index"),
]

django/photoshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(r"^api/", include("core.api.urls")),
    re_path(r"^account/", include("allauth.urls")),
    re_path(r"^account/", include("users.urls")),
    re_path(r"^gallery/", include("gallery.urls")),
    re_path(r"", include("core.urls")),
]


# DEBUG TOOLBAR
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.insert(0, re_path("__debug__/", include(debug_toolbar.urls)))

django/users/urls.py
from django.urls import re_path

from . import views

app_name = "user"
# fmt: off
urlpatterns = [
    re_path(r"^profile/update/(?P<slug>.*)/$", views.UserUpdateView.as_view(), name="user-update"),
    re_path(r"^account/delete/(?P<slug>.*)/$", views.UserAccountDeleteView.as_view(), name="user-delete"),
]
# fmt: on

django/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.templatetags.static import static
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Main User Model with Authentication"""

    REQUIRED_FIELDS = ["email"]
    image = models.ImageField(
        upload_to="users",
        help_text=_("user profile image "),
        blank=True,
        null=True,
    )
    slug = models.SlugField(editable=False)

    def save(self, **kwargs):
        self.slug = slugify(self.username)
        return super().save(**kwargs)

    def get_profile_pic(self):
        google_account = self.socialaccount_set.filter(provider="google")
        default_image = static("assets/defaults/default_user.jpg")
        if getattr(self, "image", None):
            return self.image.url
        elif google_account.exists():
            google_account = google_account.first()
            image = google_account.extra_data.get("picture", default_image)
            return image

        return default_image

    def get_update_url(self):
        return reverse("user:user-update", kwargs={"slug": self.slug})

    def get_account_delete_url(self):
        return reverse("user:user-delete", kwargs={"slug": self.slug})

django/core/forms.py
from django import forms


class ContactUsForm(forms.Form):
    MESSAGE_PLACEHOLDER = "How Can We Help You?"
    NAME_PLACEHOLDER = "Your Name"
    EMAIL_PLACEHOLDER = "Your Email"

    name = forms.CharField(
        required=True,
        max_length=120,
        widget=forms.TextInput(attrs={"class": "cf-name", "placeholder": NAME_PLACEHOLDER}),
    )

    email = forms.EmailField(
        required=True,
        max_length=80,
        widget=forms.TextInput(
            attrs={
                "class": "cf-email",
                "placeholder": EMAIL_PLACEHOLDER,
            }
        ),
    )
    message = forms.CharField(
        required=True,
        max_length=500,
        widget=forms.Textarea(
            attrs={"rows": "6", "cols": "40", "class": "cf-message", "placeholder": MESSAGE_PLACEHOLDER}
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # remove annoying autofocus
        for field in self.fields:
            try:
                field.widget.attrs.pop("autofocus", None)
            except BaseException:
                pass

django/users/forms.py
from allauth.account.forms import LoginForm
from django import forms
from django.conf import settings
from django.contrib.auth import forms as userforms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from profanity.validators import validate_is_profane

User = get_user_model()


class UserUpdateForm(userforms.UserChangeForm):
    password = None
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "image",
        )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

    def validate_name(self, data):
        # Check the name for profanity
        try:
            validate_is_profane(data)
        except ValidationError:
            # Note: Profanity is not converted into Django translation, so we add our own
            # Using except block to add translation to Profanity
            raise ValidationError(_("Please remove any profanity/bad words."))
        return data

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]
        return self.validate_name(first_name)

    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]
        return self.validate_name(last_name)

    def save(self, commit=True, *args, **kwargs):
        instance = super(UserUpdateForm, self).save(commit=False)
        if commit:
            instance.save()
        return instance


class UserSignUpForm(userforms.UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserSignUpForm, self).__init__(*args, **kwargs)
        # self.fields["captcha"].label = ""
        self.fields["username"].help_text = _(
            "Required. {} characters or fewer. Letters, digits and @/./+/-/_ only.".format(
                settings.ACCOUNT_USERNAME_MAX_LENGTH
            )
        )

    # captcha = ReCaptchaField(widget=ReCaptchaV3)
    class Meta:
        model = User
        # TODO Add captcha field "captcha"
        fields = ("username", "email")
        field_order = ["username", "email", "password"]

    def clean_username(self):
        username = self.cleaned_data["username"]

        # Check the username for profanity
        try:
            validate_is_profane(username)
        except ValidationError:
            # Note: Profanity is not converted into Django translation, so we add our own
            # Using except block to add translation to Profanity
            raise ValidationError(_("Please remove any profanity/bad words."))

        if len(username) > settings.ACCOUNT_USERNAME_MAX_LENGTH:
            raise ValidationError(
                _(
                    "Please enter a username value less than the {} characters".format(
                        settings.ACCOUNT_USERNAME_MAX_LENGTH
                    )
                )
            )
        try:
            user = User.objects.filter(username__iexact=username)
            if user.exists():
                raise ValidationError(_("Sorry, that username is already taken! "))
            return username
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            user = User.objects.filter(email__iexact=email)
            if user.exists():
                raise ValidationError(_("A user is already registered with this e-mail address."))
            return email
        except User.DoesNotExist:
            return email

    def save(self, request):
        # Ensure you call the parent class's save.
        # .save() returns a User object.
        user = super(UserSignUpForm, self).save(request)
        return user


class UserLoginForm(LoginForm):
    pass


class AccountDeleteForm(forms.ModelForm):
    delete_account = forms.BooleanField(initial=False)
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "confirm-password"}),
        help_text=("Confirm password for your account"),
    )

    class Meta:
        model = User
        fields = ("delete_account", "password")

    def clean_password(self):
        """
        Validate that the password field is correct before deleting account.
        """
        password = self.cleaned_data["password"]
        if not self.user.check_password(password):
            raise ValidationError(
                _("The password you enter was incorrect"),
                code="password_incorrect",
            )
        return password

    def save(self, commit=True):
        """Delete User Account"""
        if commit:
            self.user.delete()
        return self.user

django/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.views.generic.edit import DeleteView

from .forms import AccountDeleteForm, UserUpdateForm

User = get_user_model()


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    login_url = reverse_lazy("account_login")
    template = "user/user_form.html"

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        self.object = self.get_object()
        if self.request.method == "GET":
            context["form"] = self.form_class(instance=obj)
        else:
            context["form"] = self.form_class(instance=obj, data=self.request.POST)
        return context

    def get_success_url(self):
        return self.get_object().get_update_url()


class UserAccountDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    form_class = AccountDeleteForm
    template_name = "users/user_confirm_delete.html"
    success_url = reverse_lazy("core:index")

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        self.object = self.get_object()
        if self.request.method == "GET":
            context["form"] = self.form_class(instance=obj)
        else:
            context["form"] = self.form_class(instance=obj, data=self.request.POST)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        if form.has_changed and form.is_valid():
            # send an email to user
            # delete user account
            form.save(commit=True)
            return super().form_valid(form)
        else:
            context["form"] = form
            return super().form_invalid(form)

django/templates/users/user_confirm_delete.html
{% extends 'account/snippets/account_form.html' %}
{% load  i18n  static widget_tweaks %}

{% block account_content %}
<form class="shadow-md" action="{{object.get_delete_url}}" method="POST">
  {% csrf_token %}
  <div class="space-y-6 bg-white">
    <div class="items-center w-full p-4 space-y-4 text-gray-500 md:inline-flex md:space-y-0">
      <h4 class="font-semibold text-red-600  max-w-sm mx-auto md:w-1/3">
        {% trans "Delete Account" %}
      </h4>
      <div class="max-w-sm mx-auto space-y-5 md:w-2/3">
        <div class="relative">
          {% if form.errors %}
          <div><strong class="text-red-500">{{ form.password.errors.as_ul }}</strong></div>
          {% endif %}
          <label class="text-sm text-gray-500" for="id_password">
            {% trans "Confirm password" %}
          </label>
          {% render_field form.password|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Enter First Name" style="padding:5px;" %}
        </div>
        <div class="relative mt-2">
          {% if form.errors %}
          <div><strong class="text-red-500">{{ form.delete_account.errors.as_ul }}</strong></div>
          {% endif %}
          <label class="text-sm text-bold text-red-500" for="id_delete_account">
            {% trans "Delete" %}
          </label>
          <div class="my-3">
            <div class="relative inline-block w-10 mr-2 align-middle select-none">
              {% render_field form.delete_account|add_class:"checked:text-red-500  outline-none focus:outline-none focus:ring-red-600 right-4 checked:right-0 duration-200 ease-in absolute block w-6 h-6 rounded-full bg-white border-2 appearance-none cursor-pointer"|attr:"name:toggle"|attr:"id:delete_toggler" %}
              <label for="delete_toggler" class="block overflow-hidden h-6 rounded-full bg-gray-300 cursor-pointer"></label>
            </div>
            <span class="text-gray-900 font-medium">
              Delete Account
            </span>
          </div>
        </div>
        <div class="w-full px-4 pb-4 mt-3 ml-auto text-gray-500 md:w-1/2">
          <button type="submit"
            class="py-2 px-4  bg-red-600 hover:bg-red-700 focus:ring-red-500 focus:ring-offset-red-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-lg ">
            {% trans "Delete Account" %}
          </button>
        </div>
      </div>
    </div>
</form>
{% endblock account_content %}

django/templates/users/user_form copy.html
{% extends 'base.html' %}
{% load  i18n  static widget_tweaks %}

{% block content %}
<section class="h-screen bg-gray-100 bg-opacity-50 mt-4">
  <div class="container mx-auto">
    <div class="header mb-4">
      <h2 class="text-gray-700 font-bold border-b-2 pb-2 ">
        <svg class="inline" viewBox="0 0 24 24" width="32" height="32" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="3"></circle>
          <path
            d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z">
          </path>
        </svg>
        <span>{% trans "Account Settings" %}</span>
      </h2>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-3 md:gap-5">
      <div class="artboard artboard-demo bg-base-200 border-t-2 border-indigo-400 rounded-lg shadow w-full">
        <ul class="menu flex flex-column gap-y-8 h-full w-full rounded-lg pt-8 pb-6 shadow-lg bg-base-100">
          <li>
            <a>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9">
                </path>
              </svg>
            </a>
          </li>
          <li>
            <a>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path>
              </svg>
            </a>
          </li>
          <li class="border-t-2 pt-2">
            <a class="text-2xl" href="{% url 'account_change_password' %}">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
              </svg>
              <span class="ml-5 font-semibold">
                {% trans "Change Password" %}
              </span>
            </a>
          </li>
        </ul>
      </div>
      <div class="form-wrapper col-span-2 bg-gray-100 border-t-2 border-indigo-400 rounded-lg bg-opacity-5">
        <form class="shadow-md" action="{{object.get_update_url}}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="p-4">
            <div class="max-w-sm mx-auto md:w-full md:mx-0">
              <div class="inline-flex items-center space-x-4">
                <a href="#" class="block relative">
                  <img alt="profile" src="{{object.get_profile_pic}}" class="mx-auto object-cover border-2 border-gray-500 rounded-full h-16 w-16 " />
                </a>
                <h2 class="text-gray-600">
                  {{object.username}}
                </h2>
              </div>
            </div>
            <div class="form-group my-3">
              <label class="text-sm text-gray-500" for="id_image">
                {% trans "Update profile image" %}
              </label>
              <div class="spacer py-1"></div>
              <div class="form-control">
                {{form.image}}
              </div>
            </div>
          </div>
          <div class="space-y-6 bg-white">
            <div class="items-center w-full p-4 space-y-4 text-gray-500 md:inline-flex md:space-y-0">
              <h4 class="font-semibold max-w-sm mx-auto md:w-1/3">
                {% trans "Account" %}
              </h4>
              <div class="max-w-sm mx-auto md:w-2/3">
                <div class="relative">
                  <label class="text-sm text-gray-500" for="id_email">
                    {% trans "email" %}
                  </label>
                  {% render_field form.email|attr:"autocomplete:email"|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Email" style="padding:5px;" %}
                </div>
                <div class="relative mt-2">
                  <label class="text-sm text-gray-500" for="id_username">
                    {% trans "Username" %}
                  </label>
                  {% render_field form.username|attr:"autocomplete:email"|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Username" style="padding:5px;" %}
                </div>
              </div>
            </div>
            <hr />
            <div class="items-center w-full p-4 space-y-4 text-gray-500 md:inline-flex md:space-y-0">
              <h4 class="font-semibold max-w-sm mx-auto md:w-1/3">
                {% trans "Personalinfo" %}
              </h4>
              <div class="max-w-sm mx-auto space-y-5 md:w-2/3">
                <div class="relative">
                  <label class="text-sm text-gray-500" for="id_first_name">
                    {% trans "FirstName" %}
                  </label>
                  {% render_field form.first_name|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Enter First Name" style="padding:5px;" %}
                </div>
                <div class="relative mt-2">
                  <label class="text-sm text-gray-500" for="id_last_name">
                    {% trans "Last Name" %}
                  </label>
                  {% render_field form.last_name|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Enter Last Name" style="padding:5px;" %}
                </div>
                <div class="w-full px-4 pb-4 mt-3 ml-auto text-gray-500 md:w-1/2">
                  <button type="submit"
                    class="py-2 px-4  bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-lg ">
                    {% trans "Save" %}
                  </button>
                </div>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

django/templates/users/user_form.html
{% extends 'account/snippets/account_form.html' %}
{% load  i18n  static widget_tweaks %}

{% block account_content %}
<form class="shadow-md" action="{{object.get_update_url}}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="p-4">
    <div class="max-w-sm mx-auto md:w-full md:mx-0">
      <div class="inline-flex items-center space-x-4">
        <a href="#" class="block relative">
          <img alt="profile" src="{{object.get_profile_pic}}" class="mx-auto object-cover border-2 border-gray-500 rounded-full h-16 w-16 " />
        </a>
        <h2 class="text-gray-600">
          {{object.username}}
        </h2>
      </div>
    </div>
    <div class="form-group my-3">
      {% if form.errors %}
      <div><strong class="text-red-500">{{ form.image.errors.as_ul }}</strong></div>
      {% endif %}
      <label class="text-sm text-gray-500" for="id_image">
        {% trans "Update profile image" %}
      </label>
      <div class="spacer py-1"></div>
      <div class="form-control">
        {{form.image}}
      </div>
    </div>
  </div>
  <div class="space-y-6 bg-white">
    <div class="items-center w-full p-4 space-y-4 text-gray-500 md:inline-flex md:space-y-0">
      <h4 class="font-semibold max-w-sm mx-auto md:w-1/3">
        {% trans "Account" %}
      </h4>
      <div class="max-w-sm mx-auto md:w-2/3">
        <div class="relative">
          {% if form.errors %}
          <div><strong class="text-red-500">{{ form.email.errors.as_ul }}</strong></div>
          {% endif %}
          <label class="text-sm text-gray-500" for="id_email">
            {% trans "Email" %}
          </label>
          {% render_field form.email|attr:"autocomplete:email"|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Email" style="padding:5px;" %}
        </div>
        <div class="relative mt-2">
          {% if form.errors %}
          <div><strong class="text-red-500">{{ form.username.errors.as_ul }}</strong></div>
          {% endif %}
          <label class="text-sm text-gray-500" for="id_username">
            {% trans "Username" %}
          </label>
          {% render_field form.username|attr:"autocomplete:email"|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Username" style="padding:5px;" %}
        </div>
      </div>
    </div>
    <hr />
    <div class="items-center w-full p-4 space-y-4 text-gray-500 md:inline-flex md:space-y-0">
      <h4 class="font-semibold max-w-sm mx-auto md:w-1/3">
        {% trans "Personal Info" %}
      </h4>
      <div class="max-w-sm mx-auto space-y-5 md:w-2/3">
        <div class="relative">
          {% if form.errors %}
          <div><strong class="text-red-500">{{ form.first_name.errors.as_ul }}</strong></div>
          {% endif %}
          <label class="text-sm text-gray-500" for="id_first_name">
            {% trans "First Name" %}
          </label>
          {% render_field form.first_name|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Enter First Name" style="padding:5px;" %}
        </div>
        <div class="relative mt-2">
          {% if form.errors %}
          <div><strong class="text-red-500">{{ form.last_name.errors.as_ul }}</strong></div>
          {% endif %}
          <label class="text-sm text-gray-500" for="id_last_name">
            {% trans "Last Name" %}
          </label>
          {% render_field form.last_name|add_class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"  placeholder="Enter Last Name" style="padding:5px;" %}
        </div>
        <div class="w-full px-4 pb-4 mt-3 ml-auto text-gray-500 md:w-1/2">
          <button type="submit"
            class="py-2 px-4  bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 focus:ring-offset-blue-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-lg ">
            {% trans "Save" %}
          </button>
        </div>
      </div>
    </div>
</form>
{% endblock account_content %}